### ISSUE TITLE
I can't display favicon and I can't go directly to a link

### ISSUE THREAD

**Issue by panthe** [simpleclub/url_strategy#10]
Hi,
I'm using your package for my web project but I've some problems:
1) It can't loading correctly favicons that are in icons directory and show not found error in console
2) if I try to access directly to a subpath like www.mysite.com/login it show 404 not found error, but if I go in home page and after that I navigate to the same url all works well. If I try to go with # character like this www.mysite.com/#/login all works well.

I have follow your instructions and I've put on the main method setPathUrlStrategy() and in the index.html I've add <base href="/"> directive.
Have you some tips for help me?

**Comment by creativecreatorormaybenot** [comment]
Hi :) Thanks for using the package and opening the issue @panthe 🙌 

Unfortunately, I am not quite sure I understand what you are saying.

Here is my advice (based on guessing what issues you might be facing):

1. Did you specify your favicon using **absolute** paths? Make sure the path is specified as `/icons/favicon.png` rather than `icons/favicon.png`. Otherwise, this certainly has nothing to do with this package.
2. Does it work in debug mode (using `flutter run -d chrome`)? If it works in debug mode but not in release mode, this means that you have improperly setup your site hosting. Make sure to read through https://stackoverflow.com/a/65709246/6509751, in particular the part about SPA's.

**Comment by creativecreatorormaybenot** [comment]
I will close this since I think there is not anything further we can do on the side of the package.
