### ISSUE TITLE
WillPopScope's onWillPop not called

### ISSUE THREAD

**Issue by ronytesler** [simpleclub/url_strategy#21]
When I use the '#', the onWillPop is called.
When I use PathUrlStrategy, it's not called.

I want to capture the back button (Android device and browser)

**Comment by creativecreatorormaybenot** [comment]
Hi @ronytesler, thanks for using the package and opening the issue 🙂 

To me, this problem _sounds_ unrelated. If you are confident that it is caused by the `PathUrlStrategy`, then you should open an issue at https://github.com/flutter/flutter/issues with a minimal reproducible example 👍   
The issue would not be right here because it has nothing to do with the package either way. The package only forwards to an implementation in the Flutter framework, which is why the issue should be opened at https://github.com/flutter/flutter.
