### ISSUE TITLE
MIME type issue

### ISSUE THREAD

**Issue by Silfalion** [simpleclub/url_strategy#25]
Started having a problem with the latest version of flutter where it returns that it couldn't execute the script because of  MIME type issue. When debugging it returned an AbsoluteUriImport error. Which disappeared after removing the package. It is possible to have a look into that please?

**Comment by creativecreatorormaybenot** [comment]
Hi @Silfalion - thanks for using the package and opening the issue!

This package does not implement any actual logic, it is simply a shortcut to [`PathUrlStrategy`](https://api.flutter.dev/flutter/flutter_web_plugins/PathUrlStrategy-class.html) that also compiles on mobile. Because of that, we cannot do anything about your issue here, unfortunately.

You will have to file an issue at https://github.com/flutter/flutter 👍 And I am afraid you will need to present a minimal reproducible sample to them as noone will be able to help you otherwise.
