### ISSUE TITLE
Path breaks when I am trying to access path directly from address bar.

### ISSUE THREAD

**Issue by xscotophilic** [simpleclub/url_strategy#31]
Example: on localhost https://foo.bar works and https://foo.bar/example also works.
but on server,  https://foo.bar works and https://foo.bar/example doesn't.

**Comment by creativecreatorormaybenot** [comment]
Hi @xscotophilic - thanks for using the package!

This is not an issue with the package, but I am glad to help :) If you read through [my answer on StackOverflow](https://stackoverflow.com/a/65709246/6509751), you will see the following section:

> Furthermore, when **deploying** your **production app**, you need to make sure that *every path* points to your `index.html`. If you use tools like Firebase hosting, this is done automatically for you when configuring your app as a **single page app**.  
Otherwise, you want to look up how to rewrite all paths to your `index.html` for the hosting you are using. 
>
> Essentially, you want to have a single page app, where the HTTP server serves the `index.html` for all paths.

Depending on your server, you will need to do your own research as to how to implement a **single page app**.
